### ISSUE TITLE
建议使用ECMAScript 6

### ISSUE THREAD

**Issue by gqqnbig** [StarveZhou/Escaper#1]
我看到你在用var声明变量。建议使用ECMAScript 6里的let关键字，几乎所有的var都可以被安全地替换为let，只要你没有利用JavaScript的一些奇怪特性。

用新版本的JavaScript也能提高姿势水平。

**Comment by StarveZhou** [comment]
感谢你的提示。
这是我的课程作业，当时时间比较紧张，开始使用let和class等关键字，但是发现出现了问题，没有时间解决，就选择了一个能快速开发出来的方法，而且当时考虑的更多是代码的结构。现在想一想之前用这些关键字的时候，使用的是NodeJS下的react框架，可能是裸的浏览器不支持这些新特性？
如果有时间，我会尝试重新写这个代码。
再次感谢！

**Comment by gqqnbig** [comment]
好的呢~
